### ISSUE TITLE
Design of decoder

### ISSUE THREAD

**Issue by fsk119** [lim-anggun/FgSegNet_v2#7]
Dear author,  thanks for your paper about change detection. I' m very interested in the design of decoder in your architecture. However, I am curious why you combine information in that way : alpha*f + f where alpha is average pooling of information from upper layer. Numerous papers tend to implement network like U-net in semantic segmentation field.

**Comment by lim-anggun** [comment]
Hi,
Instead of using previous knowledge from the encoder part to refining object boundaries in the decoder part (like semantic segmentation), we try something difference. We perform global average pooling of 64 features to scale the features in the decoder. This acts like giving importance to each feature slice in the decoder according to pooled weights from the encoder. We found that this way could help improving our network performance in overall (Please refer to the paper for M-FPM vs FPM ablation study). We also provide some visualizations in the journal version of this preprint paper (unavailable just for now).

feel free to reopen this issue if you have further question.
